### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by quasiben** [carsonswope/py-nvcomp#2]
We are interested in using part of these Python bindings in https://github.com/rapidsai/cudf .

1) @carsonswope are you ok with us doing this with proper attributions to you ?
2) If 1) is a yes, would you be willing to add a permissible license such as bsd-3 or apache ?

**Comment by carsonswope** [comment]
Hi @quasiben, yes definitely. I'm just glad somebody wants to use it :)

I've added the MIT license. If this doesn't work for you let me know and I can change it to one of the other options.
