### ISSUE TITLE
Integration into kvikIO

### ISSUE THREAD

**Issue by quasiben** [carsonswope/py-nvcomp#3]
@carsonswope thanks again for adding the license.   After dealing with some internal issues we were able to start integrating the bindings into a new library just for I/O.  The PR is here: https://github.com/rapidsai/kvikio/pull/24/

We decided on this library rather than cuDF because we found other folks who wanted a much smaller library to get python bindings for nvcomp or just python bindings for GDS but not _all_  of cuDF.

**Comment by carsonswope** [comment]
No problem! Glad it's working for you
